### ISSUE TITLE
解決 Docker 中的 HTTPS 憑證問題與資料庫自動建立與遷移

### ISSUE THREAD

**Issue by s35241607** [s35241607/lan-side-project#13]
### 目前在 Docker 容器中運行 ASP.NET Core 應用程式時，遇到兩個問題：

1. **HTTPS 憑證問題**
   - 在 Docker 容器中運行 ASP.NET Core 應用時，HTTPS 憑證無法正常載入或顯示錯誤。需要解決此問題，讓應用在開發環境中能夠正常使用 HTTPS。

   **解決方案：**
   - 在 Dockerfile 中加入生成和信任憑證的步驟，而不是掛載本機的憑證。
     ```dockerfile
     FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
     
     # 安裝必要工具以生成 HTTPS 憑證
     RUN apt-get update && apt-get install -y curl && apt-get clean
     
     # 生成開發憑證
     RUN dotnet dev-certs https --clean && \
         dotnet dev-certs https --trust
     
     WORKDIR /app
     EXPOSE 8080
     EXPOSE 8081
     ```

     - 這樣每次啟動 Docker 容器時，會自動生成並信任 HTTPS 憑證，無需掛載本機憑證。
     - 在 `docker-compose.yml` 中，您不需要掛載本機的憑證，而是讓 Docker 自行生成：
     ```yaml
     version: '3.8'

     services:
       lan-side-project:
         build:
           context: .
           dockerfile: Dockerfile
         ports:
           - "8080:8080"
           - "8081:8081"
         environment:
           ASPNETCORE_ENVIRONMENT: Development
           ASPNETCORE_URLS: "https://+:8080"
           ASPNETCORE_HTTPS_PORT: 8080
     ```

     這樣，您就能在 Docker 中正確使用 HTTPS 憑證，無需手動處理。

2. **資料庫自動建立與遷移問題**
   - 需要在 Docker 容器啟動時自動建立資料庫並執行資料表遷移。在資料庫已存在的情況下，應該只執行尚未應用的遷移。

   **解決方案：**
   - 在 Docker 容器啟動時自動執行資料庫遷移，您可以在 Dockerfile 中添加一個 `entrypoint` 來執行資料庫遷移，或是在 `Program.cs` 中設定它。
   
     1. **在 `Program.cs` 中加入資料庫遷移代碼：**
     ```csharp
     public static IHostBuilder CreateHostBuilder(string[] args) =>
         Host.CreateDefaultBuilder(args)
             .ConfigureWebHostDefaults(webBuilder =>
             {
                 webBuilder.UseStartup<Startup>();
             })
             .ConfigureServices((hostContext, services) =>
             {
                 var serviceProvider = services.BuildServiceProvider();
                 var dbContext = serviceProvider.GetRequiredService<ApplicationDbContext>();
                 dbContext.Database.Migrate();  // 自動執行資料庫遷移
             });
     ```

     2. **在 `docker-compose.yml` 中加入初始化資料庫的腳本：**
     如果您有需要的話，您可以將資料庫初始化腳本放在 `docker-entrypoint-initdb.d` 中，Docker 會在啟動 PostgreSQL 容器時執行這些腳本：
     ```yaml
     volumes:
       - ./init-scripts:/docker-entrypoint-initdb.d
     ```
     這樣 PostgreSQL 容器在啟動時會自動執行您的初始化腳本，包括建立資料庫結構等。
